
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: jt-group
      # configure JsonDeserializer so that we can deserialize json object as String value from kafka topic
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      # it means that trust the package com.javatechie.dto and accept all object data from it to deserialize it from kafka topic
      properties:
        spring:
          json:
            trusted:
              packages: com.javatechie.dto


server:
  port: 9292
