server:
  port: 9191

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      # configure JsonSerializer so that we can use json object as value to kafka topic
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer